### ISSUE TITLE
pickle.UnpicklingError in ginjinn predict

### ISSUE THREAD

**Issue by mareikedaubert** [AGOberprieler/GinJinn2#3] opened 2022-09-12 09:32 UTC
Hello,
I have been following the example for detecting leaf outlines from scanned herbarium sheets and applied it to my own images. However, I run into an error when trying to predict from a segmentation model:
<pre>  File &quot;/user/me/.conda/envs/ginjinn2/lib/python3.7/site-packages/torch/serialization.py&quot;, line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File &quot;/user/me/.conda/envs/ginjinn2/lib/python3.7/site-packages/torch/serialization.py&quot;, line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, &apos;&lt;&apos;.
</pre>
The error does not occur for predicting from a bounding box model and not when I run `ginjinn predict` without the `-r` option. (Apart from that the application seems to work fine for my herbarium sheets with the workflow described in the example). 
I run the pipeline on my university's HPC in a conda environment with python 3.7 and cudatoolkit 10.1.

**Comment by ulilautenschlager** [comment] 2022-09-28 22:04
I re-ran the Leucanthemum example in a new python 3.7 environment with cudatoolkit 10.1, but could not reproduce the error.
(However, when using the dataset from Gfbio, I had to add a category filter step at the beginning, see [https://ginjinn2.readthedocs.io/en/latest/example_applications.html#leucanthemum-leaf-segmentation](https://ginjinn2.readthedocs.io/en/latest/example_applications.html#leucanthemum-leaf-segmentation)).

If the error is caused by a corrupted refinement model, it could help to remove the ".segmentation-refinement" folder inside the home directory. When using `ginjinn predict` with the `-r` option, the model will then be downloaded again.

**Comment by ulilautenschlager** [comment] 2022-11-02 14:54
The problem has been fixed with v1.0.7.

**Closed as completed by ulilautenschlager** 2022-11-02 14:54 UTC
